workflows:
  version: 2
  node-build:
    jobs:
      - node8
      - node10
      - node12

version: 2
jobs:
  node-base: &node-base
    docker:
      - image: node:latest@sha256:aef1338c8538d8bf1163a75723ba64dc0299c3ba521e0b18b1a4af12df99f622
    working_directory: ~/repo
    steps:
      - run:
          name: Version
          command: |
            echo "npm: $(npm --version)"
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: npm i
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run check:prettier
      - run: npm run tslint
      - run: npm run coverage
      - run:
          name: Post coverage report to Codecov
          command: |
            curl -s https://codecov.io/bash | bash -s -- -t ${CODECOV_TOKEN}

  node8:
    <<: *node-base
    docker:
      - image: node:8@sha256:ee34b078492dc7b7137601f1c1ed3d7f2d3d82050342bdd52e182550a086131f
  node10:
    <<: *node-base
    docker:
      - image: node:10
  node12:
    <<: *node-base
    docker:
      - image: node:12
