workflows:
  version: 2
  node-build:
    jobs:
      - node8
      - node10
      - node12

version: 2
jobs:
  node-base: &node-base
    docker:
      - image: node:latest@sha256:079a042e59e2e02666380937d3207190b8a8831f4fe671f42c4e463787132772
    working_directory: ~/repo
    steps:
      - run:
          name: Version
          command: |
            echo "npm: $(npm --version)"
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: npm i
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run check:prettier
      - run: npm run tslint
      - run: npm run coverage
      - run:
          name: Post coverage report to Codecov
          command: |
            curl -s https://codecov.io/bash | bash -s -- -t ${CODECOV_TOKEN}

  node8:
    <<: *node-base
    docker:
      - image: node:8@sha256:ee25271e00572cb09d095f6b35880a284eac570c17452644bc67fd1d8dc7f9f7
  node10:
    <<: *node-base
    docker:
      - image: node:10
  node12:
    <<: *node-base
    docker:
      - image: node:12
