workflows:
  version: 2
  node-build:
    jobs:
      - node8
      - node10
      - node12

version: 2
jobs:
  node-base: &node-base
    docker:
      - image: node:latest@sha256:7f5e7a767ecffaf96d334ffea07ba4801ab26627b37423a35c1bb747cc22676b
    working_directory: ~/repo
    steps:
      - run:
          name: Version
          command: |
            echo "npm: $(npm --version)"
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: npm i
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run check:prettier
      - run: npm run tslint
      - run: npm run coverage
      - run:
          name: Post coverage report to Codecov
          command: |
            curl -s https://codecov.io/bash | bash -s -- -t ${CODECOV_TOKEN}

  node8:
    <<: *node-base
    docker:
      - image: node:8@sha256:e45a254cf0f7071ffae9a6770cce268baf1f1952f6abb55c1061bff0757b138f
  node10:
    <<: *node-base
    docker:
      - image: node:10
  node12:
    <<: *node-base
    docker:
      - image: node:12
