workflows:
  version: 2
  node-build:
    jobs:
      - node8
      - node9

version: 2
jobs:
  node-base: &node-base
    docker:
      - image: node:latest@sha256:cf2e3cd5251273c53bd5497b1a912a9956fb775710df8e015c835719f2ce7e14
    working_directory: ~/repo
    steps:
      - run:
          name: Version
          command: |
            echo "npm: $(npm --version)"
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: npm i
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run check:prettier
      - run: npm run tslint
      - run: npm run coverage
      - run:
          name: Post coverage report to Codecov
          command: |
            curl -s https://codecov.io/bash | bash -s -- -t ${CODECOV_TOKEN}

  node8:
    <<: *node-base
    docker:
      - image: node:8@sha256:deb6287c3b94e153933ed9422db4524d2ee41be00b32c88a7cd2d91d17bf8a5e
  node9:
    <<: *node-base
    docker:
      - image: node:9@sha256:5aa0756284c7f0222c2c16988fb58d6446427ac7ae8891aa50a2de721ef4191c
