workflows:
  version: 2
  node-build:
    jobs:
      - node8
      - node10
      - node11

version: 2
jobs:
  node-base: &node-base
    docker:
      - image: node:latest@sha256:fa9ac2ee6b4bab070e669f5a88da97cad75e9ed6fa785a5b3dc22b42d6c41149
    working_directory: ~/repo
    steps:
      - run:
          name: Version
          command: |
            echo "npm: $(npm --version)"
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: npm i
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run check:prettier
      - run: npm run tslint
      - run: npm run coverage
      - run:
          name: Post coverage report to Codecov
          command: |
            curl -s https://codecov.io/bash | bash -s -- -t ${CODECOV_TOKEN}

  node8:
    <<: *node-base
    docker:
      - image: node:8@sha256:5aebe186c00da3308c8fde5b3a246d1927a56947a1b51f5c4308b7318adf74f4
  node10:
    <<: *node-base
    docker:
      - image: node:10
  node11:
    <<: *node-base
    docker:
      - image: node:11
